//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beautyshop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class beautyshopEntities : DbContext
    {
        private static beautyshopEntities _context;
        public beautyshopEntities()
            : base("name=beautyshopEntities")
        { 
        }
        public static beautyshopEntities GetContext()
        {
            if (_context == null)
                _context = new beautyshopEntities();
  
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ID_Категории> ID_Категории { get; set; }
        public virtual DbSet<ID_Клиента> ID_Клиента { get; set; }
        public virtual DbSet<ID_Мастера> ID_Мастера { get; set; }
        public virtual DbSet<ID_Услуги> ID_Услуги { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Запись_на_посещение> Запись_на_посещение { get; set; }
    }
}
