//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beautyshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ID_Категории
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ID_Категории()
        {
            this.ID_Мастера = new HashSet<ID_Мастера>();
            this.ID_Услуги = new HashSet<ID_Услуги>();
            this.Запись_на_посещение = new HashSet<Запись_на_посещение>();
        }
    
        public int ID_Категории1 { get; set; }
        public string Категория { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ID_Мастера> ID_Мастера { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ID_Услуги> ID_Услуги { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Запись_на_посещение> Запись_на_посещение { get; set; }
    }
}
