//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beautyshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ID_Услуги
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ID_Услуги()
        {
            this.Запись_на_посещение = new HashSet<Запись_на_посещение>();
        }
    
        public int ID_Услуги1 { get; set; }
        public string Услуга { get; set; }
        public int Категория { get; set; }
        public decimal Цена { get; set; }
    
        public virtual ID_Категории ID_Категории { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Запись_на_посещение> Запись_на_посещение { get; set; }
    }
}
