//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beautyshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Запись_на_посещение
    {
        public int Код { get; set; }
        public int ID_клиента { get; set; }
        public int ID_категории { get; set; }
        public int ID_услуги { get; set; }
        public int ID_мастера { get; set; }
        public System.DateTime Дата_записи { get; set; }
        public System.TimeSpan Время_записи { get; set; }
    
        public virtual ID_Категории ID_Категории1 { get; set; }
        public virtual ID_Клиента ID_Клиента1 { get; set; }
        public virtual ID_Мастера ID_Мастера1 { get; set; }
        public virtual ID_Услуги ID_Услуги1 { get; set; }
    }
}
